name: Build and Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: Build for Linux (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev pkg-config libssl-dev libsqlite3-dev libsensors-dev libpcap-dev

      - name: Build
        run: cargo build --release
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tempest-monitor-linux
          path: target/release/tempest-monitor

  build-macos:
    name: Build for macOS (Silicon)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tempest-monitor-macos
          path: target/release/tempest-monitor
